SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS ADMINISTRADOR;
CREATE TABLE ADMINISTRADOR 
(
 USUARIO VARCHAR(15) PRIMARY KEY,
 CONTRASENIA VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS VEHICULOS;
CREATE TABLE VEHICULOS
(
  MATRICULA	VARCHAR(10) NOT NULL,
  CATEGORIA	VARCHAR(15) NOT NULL,
  MARCA	 VARCHAR(20) NOT NULL,
  MODELO VARCHAR(20) NOT NULL,
  COMBUSTIBLE VARCHAR(20) NOT NULL,
  NUM_PUERTAS INT NOT NULL,
  POTENCIA INT NOT NULL,
  ANYO DATE,
  TARA_MAX INT NOT NULL,
  REVISION VARCHAR(3),
  KM_PARCIALES INT,
  PLAZAS INT,
  KM_TOTALES INT,
  PRECIO_DIA DOUBLE,
  ESTADO VARCHAR(5),
  CONSTRAINT PK_MATRICULA PRIMARY KEY(MATRICULA),
  CONSTRAINT MAX_PUERTAS CHECK (NUM_PUERTAS BETWEEN 3 AND 6),
  CONSTRAINT MAX_PLAZAS CHECK (PLAZAS BETWEEN 2 AND 8),
  CONSTRAINT VALORES_REVISION CHECK( REVISION IN ('SI','NO')),
  CONSTRAINT CK_ESTADO CHECK( ESTADO IN ('alta','baja'))
);

DROP TABLE IF EXISTS CLIENTES;
CREATE TABLE CLIENTES (
DNI VARCHAR(10) NOT NULL,
POBLACION VARCHAR(30) NOT NULL,
NOMBRE VARCHAR(40) NOT NULL,
DIRECCION VARCHAR(40) NOT NULL,
COD_POSTAL INT NOT NULL,
ESTADO VARCHAR(10) NOT NULL,
TELEFONO INT NOT NULL,
CARNET_CONDUCIR VARCHAR(20) NOT NULL,
NUM_TARJ_CREDITO VARCHAR(20) NOT NULL, 
CONSTRAINT PK_DNI PRIMARY KEY (DNI),
CONSTRAINT CK_CLIENTES_ESTADO CHECK(ESTADO IN ('baja','alta'))
);


DROP TABLE IF EXISTS alquiler;
CREATE TABLE alquiler (
id INT AUTO_INCREMENT NOT NULL,
dniCliente VARCHAR(10) NOT NULL,
matricula VARCHAR(10) NOT NULL,
fechaInicio DATE NOT NULL,
fechaPrevistaEntrega DATE NOT NULL,
fechaEntrega DATE,
diasContratados INT,
kmRecorridos INT,
estadoDeposito VARCHAR(10),
numRenovaciones INT,
pagoEfectuado VARCHAR(5),
precioDia DOUBLE,
estadoAlquiler VARCHAR(5),
CONSTRAINT pk_alquiler PRIMARY KEY(id,dniCliente,matricula,fechaInicio,fechaPrevistaEntrega),
FOREIGN KEY(dniCliente) REFERENCES CLIENTES(DNI),
FOREIGN KEY (matricula) REFERENCES VEHICULOS(MATRICULA),
CONSTRAINT CK_PAGO_ALQUILER CHECK (pagoEfectuado IN ('SI','NO')),
CONSTRAINT CK_ESTADO_ALQUILER CHECK(estadoAlquiler IN ('alta','baja'))
);

DROP TABLE if exists reserva;
CREATE TABLE reserva (
dniCliente VARCHAR(10) NOT NULL,
matricula VARCHAR(10) NOT NULL,
fechaInicio DATE NOT NULL,
diasContratados INT,
horaReserva TIME,
recogida VARCHAR(3),
estado VARCHAR(5),
CONSTRAINT pk_reservar PRIMARY KEY(dniCliente,matricula,fechaInicio,horaReserva),
FOREIGN KEY(dniCliente) REFERENCES CLIENTES(DNI),
FOREIGN KEY (matricula) REFERENCES VEHICULOS(MATRICULA),
CONSTRAINT CK_RESERVA_RECOGIDA CHECK (recogida IN ('SI','NO')),
CONSTRAINT CK_ESTADO CHECK(estado IN ('alta','baja'))
);

SET FOREIGN_KEY_CHECKS=1;