REM *************** VEHICULOS.SQL *****************


CREATE TABLE VEHICULOS
(
  MATRICULA	VARCHAR2(10)	NOT NULL,
  CATEGORIA	VARCHAR2(15)	NOT NULL,
  MARCA	        VARCHAR(15) NOT NULL,
  MODELO	VARCHAR2(30) NOT NULL,
  COMBUSTIBLE   VARCHAR2(15) NOT NULL,
  NUM_PUERTAS   NUMBER(1) NOT NULL,
  POTENCIA      VARCHAR(10) NOT NULL,
  AÑO           DATE,
  TARA_MAX      VARCHAR2(10) NOT NULL,
  REVISION      VARCHAR(2),
  KM_PARCIALES  NUMBER(6),
  PLAZAS        NUMBER(2),
  KM_TOTALES    NUMBER(6),
  PRECIO_DIA    NUMBER(6),
  CONSTRAINT PK_MATRICULA PRIMARY KEY(MATRICULA),
  CONSTRAINT MAX_PUERTAS CHECK (NUM_PUERTAS BETWEEN 3 AND 6),
  CONSTRAINT MAX_PLAZAS CHECK (PLAZAS BETWEEN 2 AND 8)
);

REM *************** ADMINISTRADOR.SQL *****************
CREATE TABLE ADMINISTRADOR 
(
 USUARIO  VARCHAR2(20) PRIMARY KEY,
 CONTRASEÑA  VARCHAR2(20) NOT NULL
);


INSERT INTO VEHICULOS (MATRICULA,CATEGORIA,MARCA,MODELO,COMBUSTIBLE,NUM_PUERTAS,POTENCIA,TARA_MAX)
VALUES ('1234-GHM','TURISMO','SEAT','LEON','DIESEL',3,'120CV','3000KG');

INSERT INTO VEHICULOS (MATRICULA,CATEGORIA,MARCA,MODELO,COMBUSTIBLE,NUM_PUERTAS,POTENCIA,TARA_MAX)
VALUES ('1235-GHM','TURISMO','BMW','SERIE1','DIESEL',5,'190CV','3000KG');

INSERT INTO VEHICULOS (MATRICULA,CATEGORIA,MARCA,MODELO,COMBUSTIBLE,NUM_PUERTAS,POTENCIA,TARA_MAX)
VALUES ('1275-GHM','TURISMO','RENAULT','KANGOOT','DIESEL',6,'90CV','3000KG');

INSERT INTO ADMINISTRADOR (USUARIO,CONTRASEÑA)
VALUES ('RUBEN','F_U_T_B_O_L');

INSERT INTO ADMINISTRADOR (USUARIO,CONTRASEÑA)
VALUES ('PEPELU','PEPELUMAGIC');

INSERT INTO ADMINISTRADOR (USUARIO,CONTRASEÑA)
VALUES ('ALEJANDRA','HOLAMUNDO');

INSERT INTO ADMINISTRADOR (USUARIO,CONTRASEÑA)
VALUES ('ALEJANDRO','PACMA1234');
